services:
  db:
    image: postgres:15-alpine
    container_name: postgres_si1
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init2.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  pgdata:
